Removed .py suffix from utilities in bin/; minor addition of new utilities

diff --git a/bin/videopath b/bin/videopath
--- a/bin/videopath
+++ b/bin/videopath
@@ -14,71 +14,71 @@ Examples (the following commands share the same meaning):
 EOF
 }
 
-videodir="$PROJ_HOME/res/videos"
+basedir="$PROJ_HOME/res/videos"
 
-rjust2() {
-	if [ -z "$1" ]; then
-		echo "00"
-	elif [ "$1" -lt 10 ]; then
-		echo "0$1"
-	else
-		echo "$1"
+######################################################################
+# Populate (day), ch and hr variables.                               #
+######################################################################
+parse_args() {
+	day=
+	ch=
+	hr=
+	local _pos_args=()
+	while [ -n "$1" ]; do
+		case "$1" in
+			d*=*) day="${1##*=}" ;;
+			c*=*) ch="${1##*=}"  ;;
+			h*=*) hr="${1##*=}"  ;;
+			-h|--help) show_help; exit 0; ;;
+			*) _pos_args+=("$1") ;;
+		esac
+		shift
+	done
+	case "${#_pos_args[@]}" in
+		0) ;;
+		2)
+			ch="${_pos_args[0]}"
+			hr="${_pos_args[1]}"
+			;;
+		3)
+			day="${_pos_args[0]}"
+			ch="${_pos_args[1]}"
+			hr="${_pos_args[2]}"
+			;;
+		*)
+			echo "Illegal # of position arguments" >&2
+			exit 1
+			;;
+	esac
+	if [ -z "$ch" ] || [ -z "$hr" ]; then
+		echo "CHANNEL and/or START_HOUR not specified" >&2
+		exit 1
 	fi
 }
 
-if [ "$1" = "-h" -o "$1" = "--help" ]; then
-	show_help
-	exit 0
-elif [ -n "$3" ]; then
-	if echo "${1}${2}${3}" | grep -q '='; then
-		while [ -n "$1" ]; do
-			val="${1##*=}"
-			case "${1%=*}" in
-				d*) day="$val" ;;
-				c*) ch="$val" ;;
-				h*) sthour="$val" ;;
-			esac
-			shift
-		done
-		if [ -z "$day" ]; then
-			echo "DAY unspecified" >&2
-			exit 1
-		elif [ -z "$ch" ]; then
-			echo "CHANNEL unspecified" >&2
-			exit 1
-		elif [ -z "$sthour" ]; then
-			echo "START_HOUR unspecified" >&2
-			exit 1
-		fi
+
+echo_video_path() {
+	local _videoname
+	_videoname="[CH$(printf "%02d" "$ch")]$(printf "%02d" "$hr")_00_00.avi"
+	if [ -z "$day" ]; then
+		echo "$basedir/$_videoname"
+	elif [ -d "$basedir/${day}Feb13.${hr}to$(( hr + 3 ))" ]; then
+		echo "$basedir/${day}Feb13.${hr}to$(( hr + 3 ))/$_videoname"
 	else
-		day="$1"
-		ch="$2"
-		sthour="$3"
-	fi
-	echo "$videodir/${day}Feb13.${sthour}to$((${sthour}+3))/[CH$(rjust2 "$ch")]$(rjust2 "$sthour")_00_00.avi"
-elif [ -n "$2" ]; then
-	if echo "${1}${2}" | grep -q '='; then
-		while [ -n "$1" ]; do
-			val="${1##*=}"
-			case "${1%=*}" in
-				c*) ch="$val" ;;
-				h*) sthour="$val" ;;
-			esac
-			shift
-		done
-		if [ -z "$ch" ]; then
-			echo "CHANNEL unspecified" >&2
-			exit 1
-		elif [ -z "$sthour" ]; then
-			echo "START_HOUR unspecified" >&2
-			exit 1
+		if find "$basedir/" -mindepth 1 -maxdepth 1 -type d -name "${day}Feb13.${hr}to*" | grep -q ''; then
+			echo "$(find "$basedir/" -mindepth 1 -maxdepth 1 -type d -name "${day}Feb13.${hr}to*" | head -1)/$_videoname"
+		else
+			echo "$basedir/${day}Feb13.${hr}to$(( hr + 3 ))/$_videoname"
 		fi
-	else
-		ch="$1"
-		sthour="$2"
 	fi
-	echo "$videodir/[CH$(rjust2 "$ch")]$(rjust2 "$sthour")_00_00.avi"
-else
-	echo "Illegal # of arguments" >&2
-	exit 1
+}
+
+
+_videopath=
+parse_args "$@"
+_videopath=$(echo_video_path)
+if [ ! -f "$_videopath" ]; then
+	echo "file not found: $_videopath" >&2
+	exit 4
 fi
+echo "$_videopath"
